# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/settings',
                'doc_host': 'https://doyu.github.io',
                'git_url': 'https://github.com/doyu/settings',
                'lib_path': 'settings'},
  'syms': {'settings.core': {'settings.core.foo': ('core.html#foo', 'settings/core.py')}}}
