# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/yttoc',
                'doc_host': 'https://doyu.github.io',
                'git_url': 'https://github.com/doyu/yttoc',
                'lib_path': 'yttoc'},
  'syms': {'yttoc.core': {'yttoc.core.foo': ('core.html#foo', 'yttoc/core.py')}}}
