"""Answer questions about a video course using LLM tool use over the yttoc cache"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/06_ask.ipynb.

# %% auto #0
__all__ = ['SYSTEM_PROMPT', 'TOOLS', 'ANSWER_SCHEMA', 'format_citations', 'ask', 'yttoc_ask']

# %% ../nbs/06_ask.ipynb #12a6289f
import json, sys
from pathlib import Path

# %% ../nbs/06_ask.ipynb #b57a20ff
SYSTEM_PROMPT = """You are answering questions about a video course.
Use the provided tools to look up information. Do not fabricate content.
Answer in the user's language. If data is unavailable, say so."""

TOOLS = [
    {
        "type": "function",
        "name": "get_summaries",
        "description": "Return the full summaries.json for a cached video. Contains: video metadata (id, title, url, channel, duration), all sections (path, title, start/end seconds, summary, keywords, evidence with timestamp), and a full-video summary. Returns {\"error\": \"...\"} if the video is not prepared.",
        "parameters": {
            "type": "object",
            "properties": {
                "video_id": {"type": "string", "description": "YouTube video ID"}
            },
            "required": ["video_id"],
        },
    },
    {
        "type": "function",
        "name": "get_xscript_range",
        "description": "Return raw parsed transcript segments within a time range [start, end). Each segment is {start: float_seconds, end: float_seconds, text: string}. Use start/end values from get_summaries sections. Returns {\"error\": \"...\"} if captions are not available.",
        "parameters": {
            "type": "object",
            "properties": {
                "video_id": {"type": "string", "description": "YouTube video ID"},
                "start": {"type": "number", "description": "Start time in seconds"},
                "end": {"type": "number", "description": "End time in seconds"},
            },
            "required": ["video_id", "start", "end"],
        },
    },
]

ANSWER_SCHEMA = {
    "type": "json_schema",
    "name": "course_answer",
    "strict": True,
    "schema": {
        "type": "object",
        "properties": {
            "answer": {"type": "string", "description": "Synthesized answer to the question"},
            "citations": {
                "type": "array",
                "items": {
                    "type": "object",
                    "properties": {
                        "video_id": {"type": "string"},
                        "seconds": {"type": "integer"},
                    },
                    "required": ["video_id", "seconds"],
                    "additionalProperties": False,
                },
            },
        },
        "required": ["answer", "citations"],
        "additionalProperties": False,
    },
}

# %% ../nbs/06_ask.ipynb #d2cf5745
from .summarize import get_summaries as _read_summaries
from .xscript import get_xscript_range as _read_xscript_range
from .core import fmt_duration

def _find_section(sections: list[dict], seconds: int) -> dict | None:
    "Find the section containing the given timestamp. Returns None if no match."
    for s in sections:
        if s['start'] <= seconds < s['end']:
            return s
    return None

def format_citations(citations: list[dict], # [{video_id, seconds}, ...]
                     root: Path = None # Cache root for summaries lookup
                    ) -> list[str]: # Formatted citation lines
    "Resolve [{video_id, seconds}] into display lines with YouTube deep links."
    from yttoc.fetch import _DEFAULT_ROOT
    root = root or _DEFAULT_ROOT
    lines = []
    for i, c in enumerate(citations, 1):
        vid, sec = c['video_id'], c['seconds']
        url = f'https://youtu.be/{vid}?t={sec}'
        ts = fmt_duration(sec)
        sums = _read_summaries(vid, root)
        if 'error' in sums:
            lines.append(f'  [{i}] {vid} @ {ts}\n      {url}')
            continue
        title = sums['video'].get('title', vid)
        section = _find_section(sums['sections'], sec)
        if section:
            lines.append(f'  [{i}] {title} \u00a7{section["path"]} "{section["title"]}" @ {ts}\n      {url}')
        else:
            lines.append(f'  [{i}] {title} @ {ts}\n      {url}')
    return lines

# %% ../nbs/06_ask.ipynb #2ea57f02
def _dispatch_tool(name: str, args: dict, root: Path) -> str:
    "Execute a tool call and return the JSON-serialized result."
    if name == 'get_summaries':
        result = _read_summaries(args['video_id'], root)
    elif name == 'get_xscript_range':
        result = _read_xscript_range(args['video_id'], args['start'], args['end'], root)
    else:
        result = {'error': f'Unknown tool: {name}'}
    return json.dumps(result, ensure_ascii=False)

# %% ../nbs/06_ask.ipynb #ae69b791
import openai

def ask(question: str, # Natural-language query
        video_ids: list[str], # Cached video IDs
        model: str = 'gpt-4o', # LLM model
        max_iterations: int = 20, # Safety cap on tool-use loop
        root: Path = None, # Cache root directory
        verbose: bool = True # Print tool calls to stderr
       ) -> dict: # {answer: str, citations: [{video_id, seconds}]}
    "Run a tool-use loop to answer a question about a video course."
    from yttoc.fetch import _DEFAULT_ROOT
    root = root or _DEFAULT_ROOT
    client = openai.OpenAI()

    user_input = f"Video IDs: {json.dumps(video_ids)}\n---\nQuestion: {question}"

    response = client.responses.create(
        model=model,
        instructions=SYSTEM_PROMPT,
        input=user_input,
        tools=TOOLS,
        text={"format": ANSWER_SCHEMA},
    )

    for _ in range(max_iterations):
        tool_calls = [item for item in response.output
                      if item.type == 'function_call']
        if not tool_calls:
            break

        tool_outputs = []
        for tc in tool_calls:
            args = json.loads(tc.arguments)
            if verbose:
                print(f'{tc.name}({", ".join(f"{k}={v!r}" for k,v in args.items())})',
                      file=sys.stderr)
            result = _dispatch_tool(tc.name, args, root)
            tool_outputs.append({
                'type': 'function_call_output',
                'call_id': tc.call_id,
                'output': result,
            })

        response = client.responses.create(
            model=model,
            previous_response_id=response.id,
            input=tool_outputs,
        )

    text_items = [item for item in response.output if item.type == 'text']
    if not text_items:
        return {'answer': 'No answer generated.', 'citations': []}
    return json.loads(text_items[0].text)

# %% ../nbs/06_ask.ipynb #098006d7
from fastcore.script import call_parse, Param

@call_parse
def yttoc_ask(question: str, # Natural-language query
              ids: Param('Cached video IDs (1+ required)', str, nargs='+'), # Video IDs
              model: str = 'gpt-4o', # LLM model
              max_iterations: int = 20, # Safety cap on tool-use loop
              root: str = None, # Root cache directory
              verbose: bool = False, # Show tool-use trace on stderr
             ):
    "Answer a question about a video course using LLM tool use."
    from yttoc.fetch import _DEFAULT_ROOT
    root_path = Path(root) if root else _DEFAULT_ROOT

    result = ask(question, ids, model=model, max_iterations=max_iterations,
                 root=root_path, verbose=verbose)

    print(result['answer'])

    if result['citations']:
        lines = format_citations(result['citations'], root_path)
        print()
        print('Citations:')
        for line in lines:
            print(line)
