"""Answer questions about a video course using LLM tool use over the yttoc cache"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/06_ask.ipynb.

# %% auto #0
__all__ = ['SYSTEM_PROMPT', 'TOOLS', 'ANSWER_SCHEMA', 'format_citations']

# %% ../nbs/06_ask.ipynb #12a6289f
import json, sys
from pathlib import Path

# %% ../nbs/06_ask.ipynb #b57a20ff
SYSTEM_PROMPT = """You are answering questions about a video course.
Use the provided tools to look up information. Do not fabricate content.
Answer in the user's language. If data is unavailable, say so."""

TOOLS = [
    {
        "type": "function",
        "name": "get_summaries",
        "description": "Return the full summaries.json for a cached video. Contains: video metadata (id, title, url, channel, duration), all sections (path, title, start/end seconds, summary, keywords, evidence with timestamp), and a full-video summary. Returns {\"error\": \"...\"} if the video is not prepared.",
        "parameters": {
            "type": "object",
            "properties": {
                "video_id": {"type": "string", "description": "YouTube video ID"}
            },
            "required": ["video_id"],
        },
    },
    {
        "type": "function",
        "name": "get_xscript_range",
        "description": "Return raw parsed transcript segments within a time range [start, end). Each segment is {start: float_seconds, end: float_seconds, text: string}. Use start/end values from get_summaries sections. Returns {\"error\": \"...\"} if captions are not available.",
        "parameters": {
            "type": "object",
            "properties": {
                "video_id": {"type": "string", "description": "YouTube video ID"},
                "start": {"type": "number", "description": "Start time in seconds"},
                "end": {"type": "number", "description": "End time in seconds"},
            },
            "required": ["video_id", "start", "end"],
        },
    },
]

ANSWER_SCHEMA = {
    "type": "json_schema",
    "name": "course_answer",
    "strict": True,
    "schema": {
        "type": "object",
        "properties": {
            "answer": {"type": "string", "description": "Synthesized answer to the question"},
            "citations": {
                "type": "array",
                "items": {
                    "type": "object",
                    "properties": {
                        "video_id": {"type": "string"},
                        "seconds": {"type": "integer"},
                    },
                    "required": ["video_id", "seconds"],
                    "additionalProperties": False,
                },
            },
        },
        "required": ["answer", "citations"],
        "additionalProperties": False,
    },
}

# %% ../nbs/06_ask.ipynb #d2cf5745
from .summarize import get_summaries as _read_summaries
from .xscript import get_xscript_range as _read_xscript_range
from .core import fmt_duration

def _find_section(sections: list[dict], seconds: int) -> dict | None:
    "Find the section containing the given timestamp. Returns None if no match."
    for s in sections:
        if s['start'] <= seconds < s['end']:
            return s
    return None

def format_citations(citations: list[dict], # [{video_id, seconds}, ...]
                     root: Path = None # Cache root for summaries lookup
                    ) -> list[str]: # Formatted citation lines
    "Resolve [{video_id, seconds}] into display lines with YouTube deep links."
    from yttoc.fetch import _DEFAULT_ROOT
    root = root or _DEFAULT_ROOT
    lines = []
    for i, c in enumerate(citations, 1):
        vid, sec = c['video_id'], c['seconds']
        url = f'https://youtu.be/{vid}?t={sec}'
        ts = fmt_duration(sec)
        sums = _read_summaries(vid, root)
        if 'error' in sums:
            lines.append(f'  [{i}] {vid} @ {ts}\n      {url}')
            continue
        title = sums['video'].get('title', vid)
        section = _find_section(sums['sections'], sec)
        if section:
            lines.append(f'  [{i}] {title} \u00a7{section["path"]} "{section["title"]}" @ {ts}\n      {url}')
        else:
            lines.append(f'  [{i}] {title} @ {ts}\n      {url}')
    return lines
