"""Answer questions about a video course using LLM tool use over the yttoc cache"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/06_ask.ipynb.

# %% auto #0
__all__ = ['SYSTEM_PROMPT', 'GetSummariesArgs', 'GetXscriptRangeArgs', 'Citation', 'AskResponse', 'ToolEntry', 'make_tool',
           'openai_tools', 'dispatch_tool', 'format_citations', 'build_registry', 'ask', 'yttoc_ask']

# %% ../nbs/06_ask.ipynb #12a6289f
import json, sys
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Callable
from pydantic import BaseModel, Field

# %% ../nbs/06_ask.ipynb #b57a20ff
SYSTEM_PROMPT = """You are answering questions about a video course.
Use the provided tools to look up information. Do not fabricate content.
Answer in the user's language. If data is unavailable, say so."""

# --- Tool input schemas (Pydantic = single schema source) ---

class GetSummariesArgs(BaseModel):
    video_id: str = Field(description="YouTube video ID")

class GetXscriptRangeArgs(BaseModel):
    video_id: str = Field(description="YouTube video ID")
    start: float = Field(ge=0, description="Start time in seconds")
    end: float = Field(ge=0, description="End time in seconds")

# --- Final structured output ---

class Citation(BaseModel):
    video_id: str = Field(description="YouTube video ID")
    seconds: int = Field(ge=0, description="Timestamp in seconds")

class AskResponse(BaseModel):
    answer: str = Field(description="Synthesized answer to the user's question")
    citations: list[Citation] = Field(default_factory=list,
        description="Deep-link citations as {video_id, seconds}")

# --- Tool registry ---

@dataclass
class ToolEntry:
    """One tool in the registry — like a C struct bundling schema + handler."""
    schema: dict[str, Any]       # OpenAI function-call schema
    args_model: type[BaseModel]  # Pydantic model for arg validation
    handler: Callable[..., Any]  # The function to call

def make_tool(name: str, description: str,
              args_model: type[BaseModel],
              handler: Callable[..., Any]) -> ToolEntry:
    "Bundle a tool's schema, arg model, and handler into a ToolEntry."
    return ToolEntry(
        schema={
            'type': 'function',
            'name': name,
            'description': description,
            'parameters': {
                **args_model.model_json_schema(),
                'additionalProperties': False,
            },
        },
        args_model=args_model,
        handler=handler,
    )

def openai_tools(registry: dict[str, ToolEntry]) -> list[dict[str, Any]]:
    "Extract OpenAI tool schemas from a registry."
    return [tool.schema for tool in registry.values()]

def _to_jsonable(o):
    "Recursively convert Pydantic BaseModel instances to dicts for JSON serialization."
    if isinstance(o, BaseModel): return o.model_dump()
    if isinstance(o, list): return [_to_jsonable(x) for x in o]
    if isinstance(o, dict): return {k: _to_jsonable(v) for k, v in o.items()}
    return o

def dispatch_tool(registry: dict[str, ToolEntry], name: str, raw_args: str) -> str:
    "Validate args via Pydantic, call handler, return JSON result."
    tool = registry.get(name)
    if tool is None:
        return json.dumps({'error': f'Unknown tool: {name}'}, ensure_ascii=False)
    try:
        args = tool.args_model.model_validate_json(raw_args)
        result = tool.handler(**args.model_dump())
    except Exception as e:
        result = {'error': str(e)}
    try:
        return json.dumps(_to_jsonable(result), ensure_ascii=False)
    except (TypeError, ValueError) as e:
        return json.dumps({'error': f'Serialization failed: {e}'}, ensure_ascii=False)

# %% ../nbs/06_ask.ipynb #d2cf5745
from pydantic import ValidationError
from .summarize import _get_summaries_strict as _read_summaries, AssembledSection
from .xscript import _get_xscript_range_strict as _read_xscript_range
from .core import fmt_duration

def _find_section(sections: list[AssembledSection], seconds: int) -> AssembledSection | None:
    "Find the section containing the given timestamp. Returns None if no match."
    for s in sections:
        if s.start <= seconds < s.end:
            return s
    return None

def format_citations(citations: list[Citation], # List of Citation objects
                     root: Path = None # Cache root for summaries lookup
                    ) -> list[str]: # Formatted citation lines
    "Resolve Citation objects into display lines with YouTube deep links."
    from yttoc.fetch import _DEFAULT_ROOT
    root = root or _DEFAULT_ROOT
    lines = []
    for i, c in enumerate(citations, 1):
        vid, sec = c.video_id, c.seconds
        url = f'https://youtu.be/{vid}?t={sec}'
        ts = fmt_duration(sec)
        try:
            sums = _read_summaries(vid, root)
        except (FileNotFoundError, ValidationError):
            lines.append(f'  [{i}] {vid} @ {ts}\n      {url}')
            continue
        title = sums.video.title
        section = _find_section(sums.sections, sec)
        if section:
            lines.append(f'  [{i}] {title} \u00a7{section.path} "{section.title}" @ {ts}\n      {url}')
        else:
            lines.append(f'  [{i}] {title} @ {ts}\n      {url}')
    return lines

def build_registry(root: Path) -> dict[str, ToolEntry]:
    "Build the tool registry with handlers bound to the given cache root."
    return {
        'get_summaries': make_tool(
            name='get_summaries',
            description='Return summaries.json verbatim for one cached video.',
            args_model=GetSummariesArgs,
            handler=lambda video_id: _read_summaries(video_id, root),
        ),
        'get_xscript_range': make_tool(
            name='get_xscript_range',
            description='Return raw parsed transcript segments within [start, end).',
            args_model=GetXscriptRangeArgs,
            handler=lambda video_id, start, end: _read_xscript_range(video_id, start, end, root),
        ),
    }


# %% ../nbs/06_ask.ipynb #ae69b791
import openai

def ask(question: str, # Natural-language query
        video_ids: list[str], # Cached video IDs
        model: str = 'gpt-4o', # LLM model
        max_iterations: int = 20, # Safety cap on tool-use loop
        root: Path = None, # Cache root directory
        verbose: bool = False # Print tool calls to stderr
       ) -> AskResponse:
    "Run a tool-use loop to answer a question about a video course."
    from yttoc.fetch import _DEFAULT_ROOT
    root = root or _DEFAULT_ROOT
    client = openai.OpenAI()
    registry = build_registry(root)
    tools = openai_tools(registry)

    user_input = f"Video IDs: {json.dumps(video_ids)}\n---\nQuestion: {question}"

    response = client.responses.parse(
        model=model,
        instructions=SYSTEM_PROMPT,
        input=user_input,
        tools=tools,
        text_format=AskResponse,
    )

    for _ in range(max_iterations):
        tool_calls = [item for item in response.output
                      if item.type == 'function_call']
        if not tool_calls:
            break

        tool_outputs = []
        for tc in tool_calls:
            if verbose:
                args = json.loads(tc.arguments)
                print(f'{tc.name}({", ".join(f"{k}={v!r}" for k,v in args.items())})',
                      file=sys.stderr)
            result = dispatch_tool(registry, tc.name, tc.arguments)
            tool_outputs.append({
                'type': 'function_call_output',
                'call_id': tc.call_id,
                'output': result,
            })

        response = client.responses.parse(
            model=model,
            previous_response_id=response.id,
            input=tool_outputs,
            tools=tools,
            text_format=AskResponse,
        )

    if hasattr(response, 'output_parsed') and response.output_parsed is not None:
        return response.output_parsed

    return AskResponse(answer='No answer generated.', citations=[])

# %% ../nbs/06_ask.ipynb #098006d7
from fastcore.script import call_parse, Param

@call_parse
def yttoc_ask(question: str, # Natural-language query
              ids: Param('Cached video IDs (1+ required)', str, nargs='+'), # Video IDs
              model: str = 'gpt-4o', # LLM model
              max_iterations: int = 20, # Safety cap on tool-use loop
              root: str = None, # Root cache directory
              verbose: bool = False, # Show tool-use trace on stderr
             ):
    "Answer a question about a video course using LLM tool use."
    from yttoc.fetch import _DEFAULT_ROOT
    root_path = Path(root) if root else _DEFAULT_ROOT

    result = ask(question, ids, model=model, max_iterations=max_iterations,
                 root=root_path, verbose=verbose)

    print(result.answer)

    if result.citations:
        lines = format_citations(result.citations, root_path)
        print()
        print('Citations:')
        for line in lines:
            print(line)
