"""Thin helpers for cache paths and generic model loading"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/07_cache.ipynb.

# %% auto #0
__all__ = ['TModel', 'resolve_root', 'video_dir', 'meta_path', 'toc_path', 'summaries_path', 'first_srt_path', 'read_model',
           'load_meta']

# %% ../nbs/07_cache.ipynb #g1000004
from pathlib import Path
from typing import TypeVar
from pydantic import BaseModel
from .core import Meta
from .fetch import _DEFAULT_ROOT, _glob_srt

TModel = TypeVar('TModel', bound=BaseModel)


# %% ../nbs/07_cache.ipynb #g1000005
def resolve_root(root: str | Path | None = None # Explicit root override
                ) -> Path: # Resolved cache root
    "Return the effective cache root as a Path."
    return Path(root) if root else _DEFAULT_ROOT

def video_dir(video_id: str, # Exact video_id
              root: str | Path | None = None # Cache root override
             ) -> Path: # Video cache directory
    "Return the cache directory for one video."
    return resolve_root(root) / video_id

def meta_path(video_id: str, # Exact video_id
              root: str | Path | None = None # Cache root override
             ) -> Path: # Path to meta.json
    "Return the path to meta.json for one video."
    return video_dir(video_id, root) / 'meta.json'

def toc_path(video_id: str, # Exact video_id
             root: str | Path | None = None # Cache root override
            ) -> Path: # Path to toc.json
    "Return the path to toc.json for one video."
    return video_dir(video_id, root) / 'toc.json'

def summaries_path(video_id: str, # Exact video_id
                   root: str | Path | None = None # Cache root override
                  ) -> Path: # Path to summaries.json
    "Return the path to summaries.json for one video."
    return video_dir(video_id, root) / 'summaries.json'

def first_srt_path(video_id: str, # Exact video_id
                   root: str | Path | None = None # Cache root override
                  ) -> Path: # First matching captions.*.srt path
    "Return the first cached SRT path for one video or raise if none exist."
    matches = _glob_srt(video_dir(video_id, root))
    if not matches:
        raise FileNotFoundError(f'No captions found for {video_id}')
    return matches[0]

def read_model(path: str | Path, # JSON file path
               model_cls: type[TModel] # Pydantic model class
              ) -> TModel: # Parsed model instance
    "Read a JSON file and validate it with the caller-provided Pydantic model class."
    path = Path(path)
    return model_cls.model_validate_json(path.read_text(encoding='utf-8'))

def load_meta(video_id: str, # Exact video_id
              root: str | Path | None = None # Cache root override
             ) -> Meta: # Parsed Meta instance
    "Load meta.json for one cached video."
    return read_model(meta_path(video_id, root), Meta)

