"""YouTube Transcript to structured Table of Contents"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_core.ipynb.

# %% auto #0
__all__ = ['Segment', 'fmt_duration', 'format_header', 'slice_segments', 'format_toc_line']

# %% ../nbs/00_core.ipynb #ec3460e1
from pydantic import BaseModel, Field

class Segment(BaseModel):
    "One parsed xscript segment (in-memory)."
    start: float = Field(ge=0, description="Start time in seconds")
    end: float = Field(ge=0, description="End time in seconds")
    text: str = Field(description="Normalized cue text")

def fmt_duration(seconds: int # Duration in seconds
                ) -> str: # Formatted as H:MM:SS or M:SS
    "Format seconds as human-readable duration."
    h, rem = divmod(seconds, 3600)
    m, s = divmod(rem, 60)
    return f'{h}:{m:02d}:{s:02d}' if h else f'{m}:{s:02d}'

def format_header(meta: dict # meta.json content
                 ) -> str: # Formatted header string
    "Shared header for toc/sum/raw CLI commands."
    title = meta.get('title', '')
    channel = meta.get('channel', '')
    dur = fmt_duration(meta.get('duration', 0))
    upload = meta.get('upload_date', '')
    return f'# {title}\nChannel: {channel} | Duration: {dur} | {upload}'

def slice_segments(segments: list[Segment], # List of Segment
                   start: int, # Section start in seconds
                   end: int # Section end in seconds
                  ) -> list[Segment]: # Segments within [start, end)
    "Return segments with start time inside [start, end)."
    return [s for s in segments if s.start >= start and s.start < end]

def format_toc_line(section: dict, # {path, title, start, end}
                    url: str = '' # webpage_url for &t= deep link (omit when empty)
                   ) -> str: # Single-line TOC entry
    "Format a TOC section as 'N. title H:MM:SS-H:MM:SS (span) URL&t=N'."
    s_start = fmt_duration(section['start'])
    s_end = fmt_duration(section['end'])
    span = fmt_duration(section['end'] - section['start'])
    suffix = f" {url}&t={section['start']}" if url else ''
    return f"{section['path']}. {section['title']} {s_start}-{s_end} ({span}){suffix}"

