"""YouTube Transcript to structured Table of Contents"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_core.ipynb.

# %% auto #0
__all__ = ['foo', 'fmt_duration', 'format_header']

# %% ../nbs/00_core.ipynb #ec3460e1
def foo(): pass

def fmt_duration(seconds: int # Duration in seconds
                ) -> str: # Formatted as H:MM:SS or M:SS
    "Format seconds as human-readable duration."
    h, rem = divmod(seconds, 3600)
    m, s = divmod(rem, 60)
    return f'{h}:{m:02d}:{s:02d}' if h else f'{m}:{s:02d}'

def format_header(meta: dict # meta.json content
                 ) -> str: # Formatted header string
    "Shared header for toc/sum/raw CLI commands."
    title = meta.get('title', '')
    channel = meta.get('channel', '')
    dur = fmt_duration(meta.get('duration', 0))
    upload = meta.get('upload_date', '')
    return f'# {title}\nChannel: {channel} | Duration: {dur} | {upload}'
