"""Download YouTube xscripts and metadata locally via yt-dlp"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/01_fetch.ipynb.

# %% auto #0
__all__ = ['load_urls', 'get_video_info', 'fetch_video', 'fetch_many']

# %% ../nbs/01_fetch.ipynb #k1vfan4sv
import json
from pathlib import Path
import yt_dlp

# %% ../nbs/01_fetch.ipynb #ebcijv1u1ji
def load_urls(path: str | Path # Path to URL list file (e.g. 'nbs/solveit2.txt')
             ) -> tuple[list[str], str]: # (urls, series_name)
    "Load URLs and derive series name from filename."
    p = Path(path)
    urls = [l.strip() for l in p.read_text(encoding='utf-8').splitlines() if l.strip()]
    series = p.stem
    return urls, series

# %% ../nbs/01_fetch.ipynb #0zd7en6efu0n
def _pick_lang(tracks: dict,
               base_lang: str = 'en' # Preferred base language
              ) -> str | None: # Best-matching language key
    "Select an exact or prefix language match from yt-dlp subtitle tracks."
    tracks = tracks or {}
    if base_lang in tracks: return base_lang
    for lang in sorted(k for k in tracks if k != 'live_chat'):
        if lang.startswith(f'{base_lang}-'):
            return lang
    return None

def _find_downloaded_srt(out_dir: str | Path # Directory containing downloaded captions
                        ) -> Path | None: # Single SRT path if present
    "Locate the downloaded SRT file emitted by yt-dlp."
    matches = sorted(Path(out_dir).glob('captions*.srt'))
    if not matches: return None
    if len(matches) > 1:
        names = ', '.join(p.name for p in matches)
        raise ValueError(f'Ambiguous caption files: {names}')
    return matches[0]

# %% ../nbs/01_fetch.ipynb #tccc8rj4sxs
def get_video_info(url: str # YouTube video URL
                  ) -> dict: # yt-dlp info dict
    "Extract video metadata and caption info without downloading."
    with yt_dlp.YoutubeDL({'skip_download': True, 'quiet': True}) as ydl:
        return ydl.extract_info(url, download=False)

# %% ../nbs/01_fetch.ipynb #irch7o3902r
def fetch_video(url: str, # YouTube video URL
                info: dict, # Result of get_video_info
                series: str, # Series name (e.g. 'solveit2')
                series_index: int, # 0-based index in series
                root: str | Path = 'downloads', # Root download directory
               ) -> Path: # Path to video directory
    "Save metadata and English srt captions for one video."
    out_dir = Path(root) / info['id']
    out_dir.mkdir(parents=True, exist_ok=True)

    srt_path = out_dir / 'captions.en.srt'
    meta_path = out_dir / 'metadata.json'
    if srt_path.exists() and meta_path.exists():
        return out_dir

    manual_lang = _pick_lang(info.get('subtitles', {}))
    auto_lang = _pick_lang(info.get('automatic_captions', {}))
    selected_lang = manual_lang or auto_lang
    if selected_lang is None:
        raise ValueError(f"No English captions available for {info['id']}")
    caption_type = 'manual' if manual_lang else 'auto'

    meta = {
        'id': info['id'],
        'title': info['title'],
        'channel': info['channel'],
        'duration': info['duration'],
        'upload_date': info['upload_date'],
        'webpage_url': info['webpage_url'],
        'caption_type': caption_type,
        'series': series,
        'series_index': series_index,
    }

    sub_opt = 'writesubtitles' if manual_lang else 'writeautomaticsub'
    opts = {
        'skip_download': True, 'quiet': True,
        sub_opt: True,
        'subtitleslangs': [selected_lang],
        'subtitlesformat': 'srt',
        'outtmpl': str(out_dir / 'captions.%(ext)s'),
    }
    with yt_dlp.YoutubeDL(opts) as ydl:
        ydl.download([url])

    downloaded = _find_downloaded_srt(out_dir)
    if downloaded is None:
        raise FileNotFoundError(f"yt-dlp did not write an srt caption for {info['id']}")
    if downloaded != srt_path:
        downloaded.replace(srt_path)

    meta_path.write_text(json.dumps(meta, indent=2, ensure_ascii=False), encoding='utf-8')
    return out_dir

# %% ../nbs/01_fetch.ipynb #mqe6eu2420j
def fetch_many(path: str | Path, # Path to URL list file
               root: str | Path = 'downloads', # Root download directory
              ) -> list[Path]: # List of output Paths
    "Fetch metadata and captions for all videos in a URL list file."
    urls, series = load_urls(path)
    results = []
    for i, url in enumerate(urls):
        print(f'[{i+1}/{len(urls)}] {url}')
        info = get_video_info(url)
        out = fetch_video(url, info, series, i, root)
        results.append(out)
    return results
