"""Download YouTube xscripts and metadata locally via yt-dlp"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/01_fetch.ipynb.

# %% auto #0
__all__ = ['get_video_info', 'fetch_video', 'yttoc_fetch']

# %% ../nbs/01_fetch.ipynb #k1vfan4sv
import json, os
from datetime import datetime, timezone
from pathlib import Path
import yt_dlp

_DEFAULT_ROOT = Path(os.environ.get('XDG_CACHE_HOME', Path.home() / '.cache')) / 'yttoc'

# %% ../nbs/01_fetch.ipynb #0zd7en6efu0n
def _pick_lang(tracks: dict,
               base_lang: str = 'en' # Preferred base language
              ) -> str | None: # Best-matching language key
    "Select an exact or prefix language match from yt-dlp subtitle tracks."
    tracks = tracks or {}
    if base_lang in tracks: return base_lang
    for lang in sorted(k for k in tracks if k != 'live_chat'):
        if lang.startswith(f'{base_lang}-'):
            return lang
    return None

def _find_downloaded_srt(out_dir: str | Path # Directory containing downloaded captions
                        ) -> Path | None: # Single SRT path if present
    "Locate the downloaded SRT file emitted by yt-dlp."
    matches = sorted(Path(out_dir).glob('captions*.srt'))
    if not matches: return None
    if len(matches) > 1:
        names = ', '.join(p.name for p in matches)
        raise ValueError(f'Ambiguous caption files: {names}')
    return matches[0]

def _update_last_used(meta_path: Path # Path to meta.json
                     ) -> None:
    "Update last_used_at timestamp in meta.json."
    meta = json.loads(meta_path.read_text(encoding='utf-8'))
    meta['last_used_at'] = datetime.now(timezone.utc).isoformat()
    meta_path.write_text(json.dumps(meta, indent=2, ensure_ascii=False), encoding='utf-8')

def _build_meta(info: dict # yt-dlp info dict
               ) -> dict: # meta.json content
    "Extract fields for meta.json from yt-dlp info."
    manual_lang = _pick_lang(info.get('subtitles', {}))
    return {
        'id': info['id'],
        'title': info['title'],
        'channel': info['channel'],
        'duration': info['duration'],
        'upload_date': info['upload_date'],
        'webpage_url': info['webpage_url'],
        'description': info.get('description', ''),
        'caption_type': 'manual' if manual_lang else 'auto',
        'last_used_at': datetime.now(timezone.utc).isoformat(),
    }

def _download_srt(url: str, info: dict, out_dir: Path) -> Path:
    "Download English SRT captions to out_dir, return final path."
    manual_lang = _pick_lang(info.get('subtitles', {}))
    auto_lang = _pick_lang(info.get('automatic_captions', {}))
    selected_lang = manual_lang or auto_lang
    if selected_lang is None:
        raise ValueError(f"No English captions available for {info['id']}")

    sub_opt = 'writesubtitles' if manual_lang else 'writeautomaticsub'
    opts = {
        'skip_download': True, 'quiet': True,
        sub_opt: True,
        'subtitleslangs': [selected_lang],
        'subtitlesformat': 'srt',
        'outtmpl': str(out_dir / 'captions.%(ext)s'),
    }
    with yt_dlp.YoutubeDL(opts) as ydl:
        ydl.download([url])

    srt_path = out_dir / 'captions.en.srt'
    downloaded = _find_downloaded_srt(out_dir)
    if downloaded is None:
        raise FileNotFoundError(f"yt-dlp did not write an srt caption for {info['id']}")
    if downloaded != srt_path:
        downloaded.replace(srt_path)
    return srt_path

# %% ../nbs/01_fetch.ipynb #tccc8rj4sxs
def get_video_info(url: str # YouTube video URL
                  ) -> dict: # yt-dlp info dict
    "Extract video metadata and caption info without downloading."
    with yt_dlp.YoutubeDL({'skip_download': True, 'quiet': True}) as ydl:
        return ydl.extract_info(url, download=False)

# %% ../nbs/01_fetch.ipynb #irch7o3902r
def fetch_video(url: str, # YouTube video URL
                info: dict, # Result of get_video_info
                root: str | Path = None, # Root download directory (default: ~/.cache/yttoc)
               ) -> Path: # Path to video directory
    "Save metadata and English srt captions for one video."
    root = Path(root) if root else _DEFAULT_ROOT
    out_dir = root / info['id']
    out_dir.mkdir(parents=True, exist_ok=True)

    srt_path = out_dir / 'captions.en.srt'
    meta_path = out_dir / 'meta.json'
    if srt_path.exists() and meta_path.exists():
        _update_last_used(meta_path)
        return out_dir

    _download_srt(url, info, out_dir)
    meta_path.write_text(json.dumps(_build_meta(info), indent=2, ensure_ascii=False), encoding='utf-8')
    return out_dir

# %% ../nbs/01_fetch.ipynb #56af6a8c
from fastcore.script import call_parse

@call_parse
def yttoc_fetch(url: str, # YouTube video URL
                root: str = None, # Root download directory (default: ~/.cache/yttoc)
               ):
    "Fetch metadata and English captions for a single YouTube video."
    info = get_video_info(url)
    out = fetch_video(url, info, root)
    print(info['id'])
