"""Download YouTube xscripts and metadata locally via yt-dlp"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/01_fetch.ipynb.

# %% auto #0
__all__ = ['get_video_info', 'fetch_video', 'yttoc_fetch', 'yttoc_list']

# %% ../nbs/01_fetch.ipynb #k1vfan4sv
import json, os
from datetime import datetime, timezone
from pathlib import Path
from pydantic import BaseModel, Field
import yt_dlp
from .core import Meta

_DEFAULT_ROOT = Path(os.environ.get('XDG_CACHE_HOME', Path.home() / '.cache')) / 'yttoc'

# %% ../nbs/01_fetch.ipynb #0zd7en6efu0n
class _YtDlpInfo(BaseModel):
    "Subset of yt-dlp info fields consumed by yttoc.fetch."
    id: str = Field(description="YouTube video ID")
    title: str = Field(description="Video title")
    channel: str = Field(description="Channel name")
    duration: int = Field(ge=0, description="Duration in seconds")
    upload_date: str = Field(description="Upload date in YYYYMMDD format")
    webpage_url: str = Field(description="Canonical YouTube URL")
    description: str = Field(default='', description="Video description (may be empty)")
    language: str | None = Field(default=None, description="Original spoken language code")
    subtitles: dict[str, list[dict[str, object]]] = Field(default_factory=dict,
        description="Manual subtitle tracks by language")
    automatic_captions: dict[str, list[dict[str, object]]] = Field(default_factory=dict,
        description="Automatic caption tracks by language")

def _coerce_video_info(info: dict | _YtDlpInfo) -> _YtDlpInfo:
    "Validate the yt-dlp fields yttoc.fetch depends on."
    if isinstance(info, _YtDlpInfo):
        return info
    return _YtDlpInfo.model_validate(info)

def _pick_lang(tracks: dict,
               base_lang: str = 'en' # Preferred base language
              ) -> str | None: # Best-matching language key
    "Select an exact or prefix language match from yt-dlp subtitle tracks."
    tracks = tracks or {}
    if base_lang in tracks: return base_lang
    for lang in sorted(k for k in tracks if k != 'live_chat'):
        if lang.startswith(f'{base_lang}-'):
            return lang
    return None

def _glob_srt(out_dir: str | Path, # Directory to search
              pattern: str = 'captions.*.srt' # Glob pattern
             ) -> list[Path]: # Sorted matching paths
    "Find SRT files matching a glob pattern."
    return sorted(Path(out_dir).glob(pattern))

def _update_last_used(meta_path: Path # Path to meta.json
                     ) -> None:
    "Update last_used_at timestamp in meta.json."
    meta = Meta.model_validate_json(meta_path.read_text(encoding='utf-8'))
    meta.last_used_at = datetime.now(timezone.utc)
    meta_path.write_text(meta.model_dump_json(indent=2), encoding='utf-8')

def _build_meta(info: dict | _YtDlpInfo, # yt-dlp info dict or validated subset
                lang: str = 'en', # Language that was fetched
                caption_type: str = 'auto' # 'manual' or 'auto'
               ) -> Meta: # Parsed Meta instance
    "Extract fields for meta.json from yt-dlp info."
    info = _coerce_video_info(info)
    meta = Meta(
        id=info.id,
        title=info.title,
        channel=info.channel,
        duration=info.duration,
        upload_date=info.upload_date,
        webpage_url=info.webpage_url,
        description=info.description,
        captions={lang: caption_type},
        last_used_at=datetime.now(timezone.utc),
    )
    return meta

def _download_srt(url: str, info: dict | _YtDlpInfo, out_dir: Path
                 ) -> tuple[Path, str, str]: # (srt_path, lang, caption_type)
    "Download SRT captions in the video's original spoken language."
    info = _coerce_video_info(info)
    base_lang = info.language
    if not base_lang:
        raise ValueError(f"Cannot determine original language for {info.id}")
    manual_lang = _pick_lang(info.subtitles, base_lang)
    auto_lang = _pick_lang(info.automatic_captions, base_lang)
    selected_lang = manual_lang or auto_lang
    if selected_lang is None:
        raise ValueError(f"No {base_lang} captions available for {info.id}")

    sub_opt = 'writesubtitles' if manual_lang else 'writeautomaticsub'
    opts = {
        'skip_download': True, 'quiet': True,
        sub_opt: True,
        'subtitleslangs': [selected_lang],
        'subtitlesformat': 'srt',
        'outtmpl': str(out_dir / f'captions_{base_lang}.%(ext)s'),
    }
    with yt_dlp.YoutubeDL(opts) as ydl:
        ydl.download([url])

    srt_path = out_dir / f'captions.{base_lang}.srt'
    matches = _glob_srt(out_dir, f'captions_{base_lang}*.srt')
    if not matches:
        raise FileNotFoundError(f"yt-dlp did not write an srt caption for {info.id}")
    if len(matches) > 1:
        raise ValueError(f"Ambiguous caption files: {', '.join(p.name for p in matches)}")
    if matches[0] != srt_path:
        matches[0].replace(srt_path)
    caption_type = 'manual' if manual_lang else 'auto'
    return srt_path, base_lang, caption_type

# %% ../nbs/01_fetch.ipynb #tccc8rj4sxs
def get_video_info(url: str # YouTube video URL
                  ) -> dict: # yt-dlp info dict
    "Extract video metadata and caption info without downloading."
    with yt_dlp.YoutubeDL({'skip_download': True, 'quiet': True}) as ydl:
        return ydl.extract_info(url, download=False)

# %% ../nbs/01_fetch.ipynb #irch7o3902r
def fetch_video(url: str, # YouTube video URL
                info: dict | _YtDlpInfo, # Result of get_video_info or validated subset
                root: str | Path = None, # Root download directory (default: ~/.cache/yttoc)
               ) -> Path: # Path to video directory
    "Save metadata and srt captions for one video in its original spoken language."
    info = _coerce_video_info(info)
    root = Path(root) if root else _DEFAULT_ROOT
    out_dir = root / info.id
    out_dir.mkdir(parents=True, exist_ok=True)

    meta_path = out_dir / 'meta.json'
    if _glob_srt(out_dir) and meta_path.exists():
        _update_last_used(meta_path)
        return out_dir

    _srt_path, lang, caption_type = _download_srt(url, info, out_dir)
    meta = _build_meta(info, lang=lang, caption_type=caption_type)
    meta_path.write_text(meta.model_dump_json(indent=2), encoding='utf-8')
    return out_dir

# %% ../nbs/01_fetch.ipynb #56af6a8c
from fastcore.script import call_parse

@call_parse
def yttoc_fetch(url: str, # YouTube video URL
                root: str = None, # Root download directory (default: ~/.cache/yttoc)
               ):
    "Fetch metadata and captions for a single YouTube video in its original spoken language."
    info = get_video_info(url)
    out = fetch_video(url, info, root)
    print(info['id'])

# %% ../nbs/01_fetch.ipynb #1c717918
from .core import fmt_duration as _fmt_duration

# %% ../nbs/01_fetch.ipynb #9e0508a9
@call_parse
def yttoc_list(root: str = None, # Root directory (default: ~/.cache/yttoc)
              ):
    "List cached videos sorted by last used."
    root = Path(root) if root else _DEFAULT_ROOT
    if not root.exists(): return

    items = []  # list of (meta: Meta, langs: str)
    for d in root.iterdir():
        if not d.is_dir(): continue
        meta_path = d / 'meta.json'
        srt_files = _glob_srt(d)
        if not (meta_path.exists() and srt_files): continue
        meta = Meta.model_validate_json(meta_path.read_text(encoding='utf-8'))
        captions = meta.captions or {p.stem.split('.', 1)[1]: '?' for p in srt_files}
        langs = ','.join(sorted(captions.keys()))
        items.append((meta, langs))

    items.sort(key=lambda x: x[0].last_used_at, reverse=True)
    for meta, langs in items:
        ts = meta.last_used_at.isoformat()[:16].replace('T', ' ')
        dur = _fmt_duration(meta.duration)
        print(f"{meta.id}  {ts}  {dur:>8}  [{langs}]  {meta.title}")

