"""Thin structured-output helper for OpenAI + Pydantic"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/08_llm.ipynb.

# %% auto #0
__all__ = ['TModel', 'generate_structured']

# %% ../nbs/08_llm.ipynb #h1000004
import json
from typing import Any, TypeVar
import openai
from pydantic import BaseModel

TModel = TypeVar('TModel', bound=BaseModel)


# %% ../nbs/08_llm.ipynb #h1000005
def generate_structured(prompt: str, # Full user prompt
                        response_model: type[TModel], # Pydantic response model
                        *,
                        schema_name: str, # JSON schema name for OpenAI response_format
                        model: str = 'gpt-5.4', # OpenAI model name
                        client: Any = None, # Optional prebuilt OpenAI-compatible client for tests
                       ) -> TModel: # Parsed response model instance
    "Call OpenAI structured output and validate into the caller-provided Pydantic model."
    client = client or openai.OpenAI()
    response = client.chat.completions.create(
        model=model,
        response_format={
            'type': 'json_schema',
            'json_schema': {
                'name': schema_name,
                'schema': response_model.model_json_schema(),
            },
        },
        messages=[{'role': 'user', 'content': prompt}],
    )
    # Some models occasionally emit trailing content after the primary JSON
    # object; extract just the first JSON value.
    content = response.choices[0].message.content
    obj, _ = json.JSONDecoder().raw_decode(content.lstrip())
    return response_model.model_validate(obj)

