"""Thin structured-output helper for OpenAI + Pydantic

Docs: https://doyu.github.io/yttocllm.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/08_llm.ipynb.

# %% auto #0
__all__ = ['TModel', 'generate_structured']

# %% ../nbs/08_llm.ipynb #h1000004
from typing import Any, TypeVar
import openai
from pydantic import BaseModel

TModel = TypeVar('TModel', bound=BaseModel)

# %% ../nbs/08_llm.ipynb #h1000005
def generate_structured(prompt: str, # Full user prompt
                        response_model: type[TModel], # Pydantic response model
                        *,
                        model: str = 'gpt-5.4', # OpenAI model name
                        client: Any = None, # Optional prebuilt OpenAI-compatible client for tests
                       ) -> TModel: # Parsed response model instance
    "Call OpenAI structured output in strict mode and return the parsed Pydantic model."
    client = client or openai.OpenAI()
    response = client.chat.completions.parse(
        model=model,
        response_format=response_model,
        messages=[{'role': 'user', 'content': prompt}],
    )
    return response.choices[0].message.parsed
