"""Generate a markmap-ready Markdown course map from cached summaries.json files"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/05_map.ipynb.

# %% auto #0
__all__ = ['FlattenedSection', 'load_summaries', 'flatten_sections', 'render_by_lecture', 'render_by_topic', 'render_by_keyword',
           'render_map', 'yttoc_map']

# %% ../nbs/05_map.ipynb #e1000005
import json
import re
from collections import Counter, defaultdict
from pathlib import Path
from pydantic import Field
from .cache import summaries_path, read_model, resolve_root
from .summarize import AssembledSection, AssembledSummaries


# %% ../nbs/05_map.ipynb #e1000006
class FlattenedSection(AssembledSection):
    "One row of the cross-video keyword/topic grid. Inherits AssembledSection fields and adds video context."
    lesson: int = Field(ge=1, description="1-based index in the lesson list")
    video_id: str = Field(description="YouTube video ID")
    video_title: str = Field(description="Video title")
    jump_url: str = Field(description="Deep-link URL for the section start")

def _norm_kw(kw: str # Raw keyword from summaries.json
            ) -> str: # Lowercased, alphanumeric-only key for grouping
    "Normalize a keyword for grouping (lowercase + drop non-alphanumerics so 'FastHTML' and 'fast html' merge)."
    return re.sub(r'[^a-z0-9]+', '', kw.lower())

def _section_label(row: FlattenedSection # Flattened section record
                  ) -> str: # 'L{lesson} §{path} {title}'
    "Short human label for a section across the whole course."
    return f"L{row.lesson} §{row.path} {row.title}"

def _canonical(originals: list[str]) -> str:
    "Pick the most frequent original casing for a normalized key. Ties resolved lexicographically (deterministic)."
    counts = Counter(originals)
    # Iterating sorted unique strings makes max() pick the lexicographically smallest on ties.
    return max(sorted(set(originals)), key=counts.get)

def load_summaries(video_ids: list[str], # Ordered video ids (lesson 1, 2, ...)
                   root: Path # Cache root dir
                  ) -> list[tuple[int, AssembledSummaries]]: # Lesson-tagged summaries
    "Load each video's summaries.json and pair with lesson number from list order."
    docs = []
    for i, vid in enumerate(video_ids, 1):
        p = summaries_path(vid, root)
        if not p.exists(): continue
        doc = read_model(p, AssembledSummaries)
        docs.append((i, doc))
    return docs

def flatten_sections(docs: list[tuple[int, AssembledSummaries]] # Lesson-tagged summaries
                    ) -> list[FlattenedSection]: # One FlattenedSection per section with video context
    "Flatten all docs into one section-level list with lesson/video metadata attached."
    rows = []
    for lesson, doc in docs:
        v = doc.video
        url = v.url or ''
        for sec in doc.sections:
            jump = f"{url}&t={sec.start}" if url else ''
            rows.append(FlattenedSection(
                **sec.model_dump(),
                lesson=lesson,
                video_id=v.id,
                video_title=v.title,
                jump_url=jump,
            ))
    return rows


# %% ../nbs/05_map.ipynb #e1000007
def render_by_lecture(docs: list[tuple[int, AssembledSummaries]] # Lesson-tagged summaries
                     ) -> str: # Markdown fragment
    "Render the By Lecture view (Lesson → sections in playback order)."
    lines = ['## By Lecture', '']
    for lesson, doc in docs:
        v = doc.video
        url = v.url or ''
        lines.append(f"- Lesson {lesson}: {v.title}")
        for sec in doc.sections:
            jump = f"{url}&t={sec.start}" if url else '#'
            lines.append(f"  - [{sec.path}. {sec.title}]({jump})")
    return '\n'.join(lines)

def _build_keyword_index(rows: list[FlattenedSection] # Flattened section rows
                        ) -> tuple[dict, dict]: # (norm → [(orig, row), ...], norm → set of lesson nums)
    "Group rows by normalized keyword, also tracking distinct lesson coverage."
    idx = defaultdict(list)
    by_lessons = defaultdict(set)
    for row in rows:
        for kw in row.keywords:
            n = _norm_kw(kw)
            if not n: continue
            idx[n].append((kw, row))
            by_lessons[n].add(row.lesson)
    return idx, by_lessons

def render_by_topic(rows: list[FlattenedSection], # Flattened section rows
                    min_lessons: int = 2 # Minimum distinct lessons for inclusion
                   ) -> str: # Markdown fragment
    "Render the By Topic view: keywords occurring in ≥ min_lessons distinct lessons."
    idx, by_lessons = _build_keyword_index(rows)
    cross = {n: pairs for n, pairs in idx.items() if len(by_lessons[n]) >= min_lessons}
    lines = ['## By Topic',
            f'_Keywords spanning ≥{min_lessons} lessons_', '']
    if not cross:
        lines.append('_(no cross-lesson topics yet)_')
        return '\n'.join(lines)
    # Sort: most lessons first, then most occurrences, then alphabetical
    sorted_keys = sorted(cross,
                         key=lambda n: (-len(by_lessons[n]), -len(cross[n]), n))
    for n in sorted_keys:
        display = _canonical([orig for orig, _ in cross[n]])
        lines.append(f"- {display} _(in {len(by_lessons[n])} lessons)_")
        for _orig, row in cross[n]:
            lines.append(f"  - [{_section_label(row)}]({row.jump_url or '#'})")
    return '\n'.join(lines)

def render_by_keyword(rows: list[FlattenedSection] # Flattened section rows
                     ) -> str: # Markdown fragment
    "Render the By Keyword view: every normalized keyword with its sections."
    idx, _ = _build_keyword_index(rows)
    lines = ['## By Keyword', '']
    for n in sorted(idx):
        display = _canonical([orig for orig, _ in idx[n]])
        lines.append(f"- {display}")
        for _orig, row in idx[n]:
            lines.append(f"  - [{_section_label(row)}]({row.jump_url or '#'})")
    return '\n'.join(lines)

_FRONTMATTER = """---
markmap:
  initialExpandLevel: 2
  maxWidth: 320
---"""

def render_map(docs: list[tuple[int, AssembledSummaries]], # Lesson-tagged summaries
               title: str = 'Course Learning Map', # Top-level heading
               min_topic_lessons: int = 2 # Threshold for By Topic inclusion
              ) -> str: # Full Markdown document
    "Render the full course map Markdown (frontmatter + 3 views)."
    rows = flatten_sections(docs)
    parts = [
        _FRONTMATTER, '',
        f'# {title}', '',
        render_by_lecture(docs), '',
        render_by_topic(rows, min_lessons=min_topic_lessons), '',
        render_by_keyword(rows),
    ]
    return '\n'.join(parts)


# %% ../nbs/05_map.ipynb #e1000009
from fastcore.script import call_parse, Param

@call_parse
def yttoc_map(ids: Param('Cached video IDs in lesson order (1+ required)', str, nargs='+'),
              title: str = 'Course Learning Map', # Top-level heading
              root: str = None, # Root cache directory
              min_topic_lessons: int = 2, # By Topic threshold (distinct lessons)
             ):
    "Generate a markmap-ready Markdown course map from cached summaries.json files."
    root = resolve_root(root)
    docs = load_summaries(ids, root)
    if not docs:
        raise SystemExit(f"No summaries.json found for: {ids}")
    print(render_map(docs, title=title, min_topic_lessons=min_topic_lessons))
