"""MCP server example for exposing yttoc tools to Claude Code, Codex, and other MCP clients"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/09_serve.ipynb.

# %% auto #0
__all__ = ['get_date', 'build_server', 'main']

# %% ../nbs/09_serve.ipynb #5600dd1b
import subprocess

# %% ../nbs/09_serve.ipynb #634f5d6f
def get_date(utc: bool = False) -> str:
    "Return the current date and time from the system clock."
    cmd = ["date", "--utc"] if utc else ["date"]
    return subprocess.run(cmd, capture_output=True, text=True, check=True).stdout.strip()

# %% ../nbs/09_serve.ipynb #2aec92a9
def build_server():
    "Create the MCP server and register yttoc tools."
    try:
        from mcp.server.fastmcp import FastMCP
    except ModuleNotFoundError as e:
        raise RuntimeError('Install MCP support with: pip install -e ".[mcp]"') from e

    mcp = FastMCP("yttoc")
    mcp.tool()(get_date)
    return mcp

# %% ../nbs/09_serve.ipynb #c97b9e75
def main():
    "Entry point for yttoc-serve CLI command."
    build_server().run()
