"""Generate section and full summaries from video xscripts via LLM"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/04_summarize.ipynb.

# %% auto #0
__all__ = ['generate_summaries', 'yttoc_sum']

# %% ../nbs/04_summarize.ipynb #c1000004
import json
from pathlib import Path

# %% ../nbs/04_summarize.ipynb #c1000005
from .core import slice_segments

def _build_summary_prompt(segments: list[dict], # Full xscript segments
                          sections: list[dict], # [{path, title, start, end}, ...] from toc.json
                          meta: dict # meta.json content
                         ) -> str: # Prompt for LLM
    "Build prompt asking LLM to summarize each section and the full video."
    parts = []
    for sec in sections:
        sliced = slice_segments(segments, sec['start'], sec['end'])
        lines = []
        for s in sliced:
            mm = int(s['start'] // 60)
            ss = int(s['start'] % 60)
            lines.append(f"[{mm:02d}:{ss:02d}] {s['text']}")
        parts.append(f"### Section {sec['path']}: {sec['title']}\n" + '\n'.join(lines))

    transcript = '\n\n'.join(parts)
    title = meta.get('title', '')
    channel = meta.get('channel', '')
    desc = meta.get('description', '')

    return f"""You are a structural editor for YouTube video transcripts.

Video info:
- Title: {title}
- Channel: {channel}
- Description: {desc}

Transcript (organized by section):
{transcript}

Task:
For each section AND for the full video, provide:
- summary: 1-2 sentence English summary
- keywords: important terms (people, technical terms, proper nouns)
- evidence: a short quoted phrase from the transcript with its timestamp in seconds

Return a JSON object with:
- "full": {{summary, keywords, evidence: {{text, at}}}}
- "sections": {{"1": {{summary, keywords, evidence: {{text, at}}}}, "2": ...}}"""

# %% ../nbs/04_summarize.ipynb #404ff620
_SUMMARY_SCHEMA = {
    "type": "object",
    "properties": {
        "full": {
            "type": "object",
            "properties": {
                "summary": {"type": "string"},
                "keywords": {"type": "array", "items": {"type": "string"}},
                "evidence": {
                    "type": "object",
                    "properties": {"text": {"type": "string"}, "at": {"type": "integer"}},
                    "required": ["text", "at"],
                },
            },
            "required": ["summary", "keywords", "evidence"],
        },
        "sections": {
            "type": "object",
            "additionalProperties": {
                "type": "object",
                "properties": {
                    "summary": {"type": "string"},
                    "keywords": {"type": "array", "items": {"type": "string"}},
                    "evidence": {
                        "type": "object",
                        "properties": {"text": {"type": "string"}, "at": {"type": "integer"}},
                        "required": ["text", "at"],
                    },
                },
                "required": ["summary", "keywords", "evidence"],
            },
        },
    },
    "required": ["full", "sections"],
}

def _call_summary_llm(prompt: str) -> dict:
    "Call OpenAI gpt-5.4 with structured output, return {full, sections} dict."
    import openai
    client = openai.OpenAI()
    response = client.chat.completions.create(
        model='gpt-5.4',
        response_format={
            "type": "json_schema",
            "json_schema": {"name": "generate_summaries", "schema": _SUMMARY_SCHEMA},
        },
        messages=[{"role": "user", "content": prompt}],
    )
    return json.loads(response.choices[0].message.content)

# %% ../nbs/04_summarize.ipynb #d286018a
from fastcore.script import call_parse
from .core import fmt_duration, format_header
from .fetch import _DEFAULT_ROOT, _update_last_used, _glob_srt
from .xscript import parse_xscript
from .toc import generate_toc

def generate_summaries(video_id: str, # Exact video_id
                       root: Path = None, # Root cache directory
                       refresh: bool = False, # Delete cached summaries and regenerate
                      ) -> dict: # {full, sections} summaries
    "Generate summaries.json for a cached video. Returns summaries dict."
    root = root or _DEFAULT_ROOT
    d = root / video_id
    meta_path = d / 'meta.json'
    sum_path = d / 'summaries.json'
    srt_files = _glob_srt(d)
    if not (meta_path.exists() and srt_files):
        raise SystemExit(f"Not cached: {video_id}")

    if refresh and sum_path.exists():
        sum_path.unlink()

    # Return cached summaries if exists
    if sum_path.exists():
        return json.loads(sum_path.read_text(encoding='utf-8'))

    # Ensure toc.json exists
    sections = generate_toc(video_id, root)

    meta = json.loads(meta_path.read_text(encoding='utf-8'))
    segments = parse_xscript(srt_files[0])
    prompt = _build_summary_prompt(segments, sections, meta)
    result = _call_summary_llm(prompt)

    sum_path.write_text(
        json.dumps(result, indent=2, ensure_ascii=False),
        encoding='utf-8')
    _update_last_used(meta_path)
    return result

@call_parse
def yttoc_sum(video_id: str, # Exact video_id
              section: str = '', # Section path (e.g. "3"); empty for all
              root: str = None, # Root cache directory
              refresh: bool = False, # Regenerate summaries
             ):
    "Display summaries for a cached video."
    root = Path(root) if root else _DEFAULT_ROOT
    d = root / video_id
    meta_path = d / 'meta.json'
    if not meta_path.exists():
        raise SystemExit(f"Not cached: {video_id}")

    meta = json.loads(meta_path.read_text(encoding='utf-8'))
    sums = generate_summaries(video_id, root, refresh=refresh)

    print(format_header(meta))
    print()

    if section:
        # Show specific section
        s = sums['sections'].get(section)
        if s is None:
            raise SystemExit(f"Section {section} not found")
        toc = json.loads((d / 'toc.json').read_text(encoding='utf-8'))
        sec_info = next((t for t in toc['sections'] if t['path'] == section), None)
        title = sec_info['title'] if sec_info else f'Section {section}'
        start = fmt_duration(sec_info['start']) if sec_info else '?'
        print(f"## {section}. {title} ({start})")
        print(s['summary'])
        print(f"**Keywords:** {', '.join(s['keywords'])}")
        print(f"**Evidence:** \"{s['evidence']['text']}\" [{fmt_duration(s['evidence']['at'])}]")
    else:
        # Show all sections + full
        for path, s in sorted(sums['sections'].items(), key=lambda x: int(x[0])):
            toc = json.loads((d / 'toc.json').read_text(encoding='utf-8'))
            sec_info = next((t for t in toc['sections'] if t['path'] == path), None)
            title = sec_info['title'] if sec_info else f'Section {path}'
            start = fmt_duration(sec_info['start']) if sec_info else '?'
            print(f"## {path}. {title} ({start})")
            print(s['summary'])
            print(f"**Keywords:** {', '.join(s['keywords'])}")
            print(f"**Evidence:** \"{s['evidence']['text']}\" [{fmt_duration(s['evidence']['at'])}]")
            print()

        print("## Full Summary")
        print(sums['full']['summary'])
        print(f"**Keywords:** {', '.join(sums['full']['keywords'])}")
        print(f"**Evidence:** \"{sums['full']['evidence']['text']}\" [{fmt_duration(sums['full']['evidence']['at'])}]")
