"""Generate section and full summaries from video xscripts via LLM"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/04_summarize.ipynb.

# %% auto #0
__all__ = ['Evidence', 'SectionSummaryPayload', 'SummaryLLMResult', 'generate_summaries', 'yttoc_sum', 'get_summaries']

# %% ../nbs/04_summarize.ipynb #c1000004
import json
from pathlib import Path
from pydantic import BaseModel, Field

# %% ../nbs/04_summarize.ipynb #c1000005
from .core import slice_segments, Segment

def _build_summary_prompt(segments: list[Segment], # Full xscript segments
                          sections: list[dict], # [{path, title, start, end}, ...] from toc.json
                          meta: dict # meta.json content
                         ) -> str: # Prompt for LLM
    "Build prompt asking LLM to summarize each section and the full video."
    parts = []
    for sec in sections:
        sliced = slice_segments(segments, sec['start'], sec['end'])
        lines = []
        for s in sliced:
            mm = int(s.start // 60)
            ss = int(s.start % 60)
            lines.append(f"[{mm:02d}:{ss:02d}] {s.text}")
        parts.append(f"### Section {sec['path']}: {sec['title']}\n" + '\n'.join(lines))

    transcript = '\n\n'.join(parts)
    title = meta.get('title', '')
    channel = meta.get('channel', '')
    desc = meta.get('description', '')

    return f"""You are a structural editor for YouTube video transcripts.

Video info:
- Title: {title}
- Channel: {channel}
- Description: {desc}

Transcript (organized by section):
{transcript}

Task:
For each section AND for the full video, provide:
- summary: 1-2 sentence English summary
- keywords: important terms (people, technical terms, proper nouns)
- evidence: a short quoted phrase from the transcript with its timestamp in seconds

Return a JSON object with:
- "full": {{summary, keywords, evidence: {{text, at}}}}
- "sections": {{"1": {{summary, keywords, evidence: {{text, at}}}}, "2": ...}}"""

# %% ../nbs/04_summarize.ipynb #404ff620
class Evidence(BaseModel):
    "A quoted phrase from the transcript with its timestamp."
    text: str = Field(description="Short quoted phrase from the transcript")
    at: int = Field(ge=0, description="Timestamp in seconds where the quote appears")

class SectionSummaryPayload(BaseModel):
    "Summary payload for one section or the full video."
    summary: str = Field(description="1-2 sentence English summary")
    keywords: list[str] = Field(description="Important terms (people, technical terms, proper nouns)")
    evidence: Evidence

class SummaryLLMResult(BaseModel):
    "Structured output from the summary generation LLM call."
    full: SectionSummaryPayload
    sections: dict[str, SectionSummaryPayload] = Field(
        description="Per-section summaries keyed by section path ('1', '2', ...)")

def _call_summary_llm(prompt: str) -> dict:
    "Call OpenAI gpt-5.4 with Pydantic-generated schema, return {full, sections} dict."
    import openai
    client = openai.OpenAI()
    response = client.chat.completions.create(
        model='gpt-5.4',
        response_format={
            "type": "json_schema",
            "json_schema": {
                "name": "generate_summaries",
                "schema": SummaryLLMResult.model_json_schema(),
            },
        },
        messages=[{"role": "user", "content": prompt}],
    )
    return SummaryLLMResult.model_validate_json(
        response.choices[0].message.content).model_dump()

# %% ../nbs/04_summarize.ipynb #d286018a
from fastcore.script import call_parse
from .core import fmt_duration, format_header, format_toc_line
from .fetch import _DEFAULT_ROOT, _update_last_used, _glob_srt
from .xscript import parse_xscript
from .toc import generate_toc

def _assemble_summaries(meta: dict, # meta.json content
                        toc_sections: list[dict], # [{path, title, start, end}, ...] from toc.json
                        llm_result: dict # {full, sections: {path: {...}}}
                       ) -> dict: # Self-contained summaries.json payload
    "Merge meta + toc + LLM output into the canonical summaries.json shape. Raise if LLM omitted any section."
    missing = [sec['path'] for sec in toc_sections if sec['path'] not in llm_result['sections']]
    if missing:
        raise ValueError(f"LLM omitted summaries for sections: {missing}")
    return {
        'video': {
            'id': meta.get('id'),
            'title': meta.get('title'),
            'channel': meta.get('channel'),
            'url': meta.get('webpage_url'),
            'duration': meta.get('duration'),
            'upload_date': meta.get('upload_date'),
        },
        'sections': [
            {'path': sec['path'], 'title': sec['title'],
             'start': sec['start'], 'end': sec['end'],
             **llm_result['sections'][sec['path']]}
            for sec in toc_sections
        ],
        'full': llm_result['full'],
    }

def _migrate_old_summaries(cached: dict, # Old-format summaries dict {full, sections: {path: {...}}}
                           video_id: str, root: Path
                          ) -> dict: # New-format summaries dict
    "Rebuild a self-contained summaries.json from the legacy {full, sections: {...}} shape."
    meta_path = root / video_id / 'meta.json'
    meta = json.loads(meta_path.read_text(encoding='utf-8'))
    toc_sections = generate_toc(video_id, root)  # cached toc.json hit; no LLM call
    return _assemble_summaries(meta, toc_sections, cached)

def generate_summaries(video_id: str, # Exact video_id
                       root: Path = None, # Root cache directory
                       refresh: bool = False, # Delete cached summaries and regenerate
                      ) -> dict: # Self-contained summaries dict
    "Generate summaries.json for a cached video. Returns summaries dict (auto-migrating old shape)."
    root = root or _DEFAULT_ROOT
    d = root / video_id
    meta_path = d / 'meta.json'
    sum_path = d / 'summaries.json'
    srt_files = _glob_srt(d)
    if not (meta_path.exists() and srt_files):
        raise SystemExit(f"Not cached: {video_id}")

    if refresh and sum_path.exists():
        sum_path.unlink()

    if sum_path.exists():
        cached = json.loads(sum_path.read_text(encoding='utf-8'))
        if 'video' in cached:
            return cached
        # Legacy shape: rebuild in place (no LLM call)
        result = _migrate_old_summaries(cached, video_id, root)
        sum_path.write_text(
            json.dumps(result, indent=2, ensure_ascii=False),
            encoding='utf-8')
        return result

    toc_sections = generate_toc(video_id, root)
    meta = json.loads(meta_path.read_text(encoding='utf-8'))
    segments = parse_xscript(srt_files[0])
    prompt = _build_summary_prompt(segments, toc_sections, meta)
    llm_result = _call_summary_llm(prompt)
    result = _assemble_summaries(meta, toc_sections, llm_result)

    sum_path.write_text(
        json.dumps(result, indent=2, ensure_ascii=False),
        encoding='utf-8')
    _update_last_used(meta_path)
    return result

def _print_section_summary(s: dict, url: str):
    "Render one section as a TOC-style header followed by summary/keywords/evidence."
    print(f"## {format_toc_line(s, url)}")
    print(s['summary'])
    print(f"**Keywords:** {', '.join(s['keywords'])}")
    print(f"**Evidence:** \"{s['evidence']['text']}\" [{fmt_duration(s['evidence']['at'])}]")

@call_parse
def yttoc_sum(video_id: str, # Exact video_id
              section: str = '', # Section path (e.g. "3"); empty for all
              root: str = None, # Root cache directory
              refresh: bool = False, # Regenerate summaries
             ):
    "Display summaries for a cached video."
    root = Path(root) if root else _DEFAULT_ROOT
    sums = generate_summaries(video_id, root, refresh=refresh)
    video = sums['video']
    url = video.get('url') or ''

    print(format_header(video))
    print()

    if section:
        s = next((sec for sec in sums['sections'] if sec['path'] == section), None)
        if s is None:
            raise SystemExit(f"Section {section} not found")
        _print_section_summary(s, url)
    else:
        for s in sums['sections']:
            _print_section_summary(s, url)
            print()

        print("## Full Summary")
        print(sums['full']['summary'])
        print(f"**Keywords:** {', '.join(sums['full']['keywords'])}")
        print(f"**Evidence:** \"{sums['full']['evidence']['text']}\" [{fmt_duration(sums['full']['evidence']['at'])}]")
        if url: print(url)

# %% ../nbs/04_summarize.ipynb #73e522f6
def get_summaries(video_id: str, # Exact video_id
                  root: Path = None # Root cache directory (default: ~/.cache/yttoc)
                 ) -> dict: # summaries.json content verbatim, or {"error": "..."}
    "Return summaries.json for a cached video. No transformation — file content returned as-is."
    root = root or _DEFAULT_ROOT
    sum_path = root / video_id / 'summaries.json'
    if not sum_path.exists():
        return {'error': f'summaries.json not found for {video_id}'}
    return json.loads(sum_path.read_text(encoding='utf-8'))
