"""Generate section and full summaries from video xscripts via LLM"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/04_summarize.ipynb.

# %% auto #0
__all__ = ['Evidence', 'SectionSummaryPayload', 'SummaryLLMResult', 'VideoBlock', 'AssembledSection', 'AssembledSummaries',
           'generate_summaries', 'yttoc_sum', 'get_summaries']

# %% ../nbs/04_summarize.ipynb #c1000004
import json
from pathlib import Path
from pydantic import BaseModel, Field
from .llm import generate_structured


# %% ../nbs/04_summarize.ipynb #c1000005
from .core import slice_segments, Segment, NormalizedSection, Meta

def _build_summary_prompt(segments: list[Segment], # Full xscript segments
                          sections: list[NormalizedSection], # List of NormalizedSection from toc.json
                          meta: Meta # Parsed Meta instance
                         ) -> str: # Prompt for LLM
    "Build prompt asking LLM to summarize each section and the full video."
    parts = []
    for sec in sections:
        sliced = slice_segments(segments, sec.start, sec.end)
        lines = []
        for s in sliced:
            mm = int(s.start // 60)
            ss = int(s.start % 60)
            lines.append(f"[{mm:02d}:{ss:02d}] {s.text}")
        parts.append(f"### Section {sec.path}: {sec.title}\n" + '\n'.join(lines))

    transcript = '\n\n'.join(parts)
    title = meta.title
    channel = meta.channel
    desc = meta.description

    return f"""You are a structural editor for YouTube video transcripts.

Video info:
- Title: {title}
- Channel: {channel}
- Description: {desc}

Transcript (organized by section):
{transcript}

Task:
For each section AND for the full video, provide:
- summary: 1-2 sentence English summary
- keywords: important terms (people, technical terms, proper nouns)
- evidence: a short quoted phrase from the transcript with its timestamp in seconds

Return a JSON object with:
- "full": {{summary, keywords, evidence: {{text, at}}}}
- "sections": {{"1": {{summary, keywords, evidence: {{text, at}}}}, "2": ...}}"""


# %% ../nbs/04_summarize.ipynb #404ff620
class Evidence(BaseModel):
    "A quoted phrase from the transcript with its timestamp."
    text: str = Field(description="Short quoted phrase from the transcript")
    at: int = Field(ge=0, description="Timestamp in seconds where the quote appears")

class SectionSummaryPayload(BaseModel):
    "Summary payload for one section or the full video."
    summary: str = Field(description="1-2 sentence English summary")
    keywords: list[str] = Field(description="Important terms (people, technical terms, proper nouns)")
    evidence: Evidence

class SummaryLLMResult(BaseModel):
    "Structured output from the summary generation LLM call."
    full: SectionSummaryPayload
    sections: dict[str, SectionSummaryPayload] = Field(
        description="Per-section summaries keyed by section path ('1', '2', ...)")

class VideoBlock(BaseModel):
    "Video header subset persisted inside summaries.json."
    id: str = Field(description="YouTube video ID")
    title: str = Field(description="Video title")
    channel: str = Field(description="Channel name")
    url: str = Field(description="Canonical YouTube URL")
    duration: int = Field(ge=0, description="Duration in seconds")
    upload_date: str = Field(description="Upload date in YYYYMMDD format")

class AssembledSection(NormalizedSection):
    "TOC section with LLM-generated summary payload."
    summary: str = Field(description="1-2 sentence summary")
    keywords: list[str] = Field(description="Important terms")
    evidence: Evidence = Field(description="Quoted phrase + timestamp")

class AssembledSummaries(BaseModel):
    "On-disk shape of summaries.json."
    video: VideoBlock
    sections: list[AssembledSection]
    full: SectionSummaryPayload

def _call_summary_llm(prompt: str) -> dict:
    "Call OpenAI gpt-5.4 with Pydantic-generated schema, return {full, sections} dict."
    return generate_structured(
        prompt, SummaryLLMResult, schema_name='generate_summaries').model_dump()


# %% ../nbs/04_summarize.ipynb #d286018a
from fastcore.script import call_parse
from .core import fmt_duration, format_header, format_toc_line, NormalizedSection, Meta
from .cache import (resolve_root, meta_path, summaries_path,
                         first_srt_path, load_meta, read_model, touch_meta)
from .xscript import parse_xscript
from .toc import generate_toc

def _assemble_summaries(meta: Meta, # Parsed Meta instance
                        toc_sections: list[NormalizedSection], # List of NormalizedSection from toc.json
                        llm_result: dict # {full, sections: {path: {...}}}
                       ) -> AssembledSummaries: # Parsed AssembledSummaries instance
    "Merge meta + toc + LLM output into the canonical summaries.json shape. Raise if LLM omitted any section."
    missing = [sec.path for sec in toc_sections if sec.path not in llm_result['sections']]
    if missing:
        raise ValueError(f"LLM omitted summaries for sections: {missing}")
    return AssembledSummaries(
        video=VideoBlock(
            id=meta.id,
            title=meta.title,
            channel=meta.channel,
            url=meta.webpage_url,
            duration=meta.duration,
            upload_date=meta.upload_date,
        ),
        sections=[
            AssembledSection(**sec.model_dump(), **llm_result['sections'][sec.path])
            for sec in toc_sections
        ],
        full=llm_result['full'],
    )

def generate_summaries(video_id: str, # Exact video_id
                       root: Path = None, # Root cache directory
                       refresh: bool = False, # Delete cached summaries and regenerate
                      ) -> AssembledSummaries: # Parsed AssembledSummaries instance
    "Generate summaries.json for a cached video. Returns parsed AssembledSummaries."
    root = resolve_root(root)
    meta_p = meta_path(video_id, root)
    sum_p = summaries_path(video_id, root)
    if not meta_p.exists():
        raise SystemExit(f"Not cached: {video_id}")
    try:
        srt_path = first_srt_path(video_id, root)
    except FileNotFoundError:
        raise SystemExit(f"Not cached: {video_id}")

    if refresh and sum_p.exists():
        sum_p.unlink()

    if sum_p.exists():
        return read_model(sum_p, AssembledSummaries)

    toc_sections = generate_toc(video_id, root)
    meta = load_meta(video_id, root)
    segments = parse_xscript(srt_path)
    prompt = _build_summary_prompt(segments, toc_sections, meta)
    llm_result = _call_summary_llm(prompt)
    result = _assemble_summaries(meta, toc_sections, llm_result)

    sum_p.write_text(result.model_dump_json(indent=2), encoding='utf-8')
    touch_meta(video_id, root)
    return result

def _format_section_summary(s: AssembledSection, # Assembled section with summary payload
                            url: str, # Canonical video URL ('' when absent)
                           ) -> list[str]: # Four-line block: TOC heading, summary, keywords, evidence
    "Format one section as a TOC-heading block."
    return [
        f"## {format_toc_line(s, url)}",
        s.summary,
        f"**Keywords:** {', '.join(s.keywords)}",
        f"**Evidence:** \"{s.evidence.text}\" [{fmt_duration(s.evidence.at)}]",
    ]

def _render_summaries(sums: AssembledSummaries, # Parsed summaries.json
                     section: str = '', # Section path; '' for all sections + full summary
                    ) -> str: # Rendered summaries output
    "Render summary output for yttoc_sum. Raise ValueError if section missing."
    url = sums.video.url or ''
    lines = [format_header(sums.video), '']
    if section:
        s = next((sec for sec in sums.sections if sec.path == section), None)
        if s is None:
            raise ValueError(f"Section {section} not found")
        lines.extend(_format_section_summary(s, url))
    else:
        for s in sums.sections:
            lines.extend(_format_section_summary(s, url))
            lines.append('')
        lines.append("## Full Summary")
        lines.append(sums.full.summary)
        lines.append(f"**Keywords:** {', '.join(sums.full.keywords)}")
        lines.append(f"**Evidence:** \"{sums.full.evidence.text}\" [{fmt_duration(sums.full.evidence.at)}]")
        if url: lines.append(url)
    return '\n'.join(lines)

@call_parse
def yttoc_sum(video_id: str, # Exact video_id
              section: str = '', # Section path (e.g. "3"); empty for all
              root: str = None, # Root cache directory
              refresh: bool = False, # Regenerate summaries
             ):
    "Display summaries for a cached video."
    root = resolve_root(root)
    sums = generate_summaries(video_id, root, refresh=refresh)
    try:
        print(_render_summaries(sums, section))
    except ValueError as e:
        raise SystemExit(str(e))

# %% ../nbs/04_summarize.ipynb #73e522f6
def _get_summaries_strict(video_id: str, # Exact video_id
                          root: Path = None # Root cache directory (default: ~/.cache/yttoc)
                         ) -> AssembledSummaries: # Parsed AssembledSummaries
    "Return validated summaries.json or raise on missing/invalid data."
    root = resolve_root(root)
    sum_p = summaries_path(video_id, root)
    if not sum_p.exists():
        raise FileNotFoundError(f'summaries.json not found for {video_id}')
    return read_model(sum_p, AssembledSummaries)

def get_summaries(video_id: str, # Exact video_id
                  root: Path = None # Root cache directory (default: ~/.cache/yttoc)
                 ) -> AssembledSummaries | dict: # Parsed AssembledSummaries or {"error": "..."}
    "Compatibility wrapper around _get_summaries_strict for tool/CLI consumers expecting {'error': ...}."
    from pydantic import ValidationError
    try:
        return _get_summaries_strict(video_id, root)
    except FileNotFoundError as e:
        return {'error': str(e)}
    except ValidationError as e:
        return {'error': f'Invalid summaries.json for {video_id}: {e}'}
