"""Generate structured Table of Contents from video xscripts via LLM"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/03_toc.ipynb.

# %% auto #0
__all__ = ['RawTocSection', 'TocLLMResult', 'TocFile', 'generate_toc', 'yttoc_toc']

# %% ../nbs/03_toc.ipynb #b1000004
import json
from pathlib import Path
from pydantic import BaseModel, Field
from .core import Segment, NormalizedSection, Meta
from .llm import generate_structured

# %% ../nbs/03_toc.ipynb #b1000005
def _normalize_sections(raw: 'list[RawTocSection]', # [RawTocSection, ...] from LLM
                        duration: int # Video duration in seconds
                       ) -> list[NormalizedSection]: # List of NormalizedSection
    "Add path/end, sort by start, dedup, validate. Raise on broken coverage."
    if not raw:
        raise ValueError("No sections returned from LLM")
    # Sort by start ascending
    sections = sorted(raw, key=lambda s: s.start)
    # Remove duplicate starts (keep first)
    seen = set()
    deduped = []
    for s in sections:
        if s.start not in seen:
            seen.add(s.start)
            deduped.append(s)
    sections = deduped
    # Fix first section start to 0 (create a new RawTocSection with start=0)
    sections[0] = sections[0].model_copy(update={'start': 0})
    # Build NormalizedSection list
    result = []
    for i, s in enumerate(sections):
        end = sections[i+1].start if i+1 < len(sections) else duration
        result.append(NormalizedSection(path=str(i+1), title=s.title, start=s.start, end=end))
    return result


# %% ../nbs/03_toc.ipynb #d95b70ae
def _build_toc_prompt(segments: list[Segment], # List of Segment from parse_xscript
                      meta: Meta # Parsed Meta instance
                     ) -> str: # Prompt for LLM
    "Build a prompt that asks the LLM to identify topic transitions and return section titles with start times."
    lines = []
    for s in segments:
        mm = int(s.start // 60)
        ss = int(s.start % 60)
        lines.append(f"[{mm:02d}:{ss:02d}] {s.text}")
    transcript = '\n'.join(lines)

    title = meta.title
    channel = meta.channel
    desc = meta.description

    return f"""You are a structural editor for YouTube video transcripts.

Video info:
- Title: {title}
- Channel: {channel}
- Description: {desc}

Transcript:
{transcript}

Task:
Read the transcript and identify topic transitions. For each section, provide:
- title: concise English section title
- start: start time in integer seconds

Aim for 7-15 sections. Be faithful to transcript timestamps."""

class RawTocSection(BaseModel):
    "One section as returned by the TOC LLM — title + start time only."
    title: str = Field(description="Concise English section title")
    start: int = Field(ge=0, description="Start time in integer seconds")

class TocLLMResult(BaseModel):
    "Structured output from the TOC generation LLM call."
    sections: list[RawTocSection]


class TocFile(BaseModel):
    "On-disk shape of toc.json."
    sections: list[NormalizedSection]

def _call_llm(prompt: str # Full prompt
             ) -> list[RawTocSection]: # List of RawTocSection
    "Call OpenAI gpt-5.4 with Pydantic-generated schema, return raw section list."
    result = generate_structured(prompt, TocLLMResult, schema_name='generate_toc')
    return result.sections


# %% ../nbs/03_toc.ipynb #795bea0d
import sys
from fastcore.script import call_parse
from .core import format_header, format_toc_line, Meta
from .cache import (resolve_root, meta_path, toc_path, summaries_path,
                         first_srt_path, load_meta, read_model)
from .fetch import _update_last_used
from .xscript import parse_xscript

def generate_toc(video_id: str, # Exact video_id
                 root: Path = None, # Root cache directory
                 refresh: bool = False, # Delete cached toc/summaries and regenerate
                ) -> list[NormalizedSection]: # List of NormalizedSection
    "Generate toc.json for a cached video. Returns sections list."
    root = resolve_root(root)
    meta_p = meta_path(video_id, root)
    toc_p = toc_path(video_id, root)
    sum_p = summaries_path(video_id, root)
    if not meta_p.exists():
        raise SystemExit(f"Not cached: {video_id}")
    try:
        srt_path = first_srt_path(video_id, root)
    except FileNotFoundError:
        raise SystemExit(f"Not cached: {video_id}")

    if refresh:
        if toc_p.exists(): toc_p.unlink()
        if sum_p.exists():
            sum_p.unlink()
            print('Invalidated summaries.json (depends on toc)', file=sys.stderr)

    if toc_p.exists():
        return read_model(toc_p, TocFile).sections

    meta = load_meta(video_id, root)
    segments = parse_xscript(srt_path)
    prompt = _build_toc_prompt(segments, meta)
    raw = _call_llm(prompt)
    sections = _normalize_sections(raw, meta.duration)

    toc_p.write_text(
        TocFile(sections=sections).model_dump_json(indent=2),
        encoding='utf-8')
    _update_last_used(meta_p)
    return sections

def _render_toc(meta: Meta, # Parsed Meta instance
                sections: list[NormalizedSection], # Normalized TOC sections
               ) -> str: # Rendered TOC: header + blank + formatted lines
    "Render TOC output for yttoc_toc."
    lines = [format_header(meta), '']
    url = meta.webpage_url
    for s in sections:
        lines.append(format_toc_line(s, url))
    return '\n'.join(lines)

@call_parse
def yttoc_toc(video_id: str, # Exact video_id
              root: str = None, # Root cache directory
              refresh: bool = False, # Regenerate toc (and invalidate summaries)
             ):
    "Generate and display Table of Contents for a cached video."
    root = resolve_root(root)
    meta_p = meta_path(video_id, root)
    if not meta_p.exists():
        raise SystemExit(f"Not cached: {video_id}")

    meta = load_meta(video_id, root)
    sections = generate_toc(video_id, root, refresh=refresh)
    print(_render_toc(meta, sections))

