"""Generate structured Table of Contents from video xscripts via LLM"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/03_toc.ipynb.

# %% auto #0
__all__ = ['RawTocSection', 'TocLLMResult', 'generate_toc', 'yttoc_toc']

# %% ../nbs/03_toc.ipynb #b1000004
import json
from pathlib import Path
from pydantic import BaseModel, Field
from .core import Segment

# %% ../nbs/03_toc.ipynb #b1000005
def _normalize_sections(raw: list[dict], # [{title, start}, ...] from LLM
                        duration: int # Video duration in seconds
                       ) -> list[dict]: # [{path, title, start, end}, ...]
    "Add path/end, sort by start, dedup, validate. Raise on broken coverage."
    if not raw:
        raise ValueError("No sections returned from LLM")
    # Sort by start ascending
    sections = sorted(raw, key=lambda s: s['start'])
    # Remove duplicate starts (keep first)
    seen = set()
    deduped = []
    for s in sections:
        if s['start'] not in seen:
            seen.add(s['start'])
            deduped.append(s)
    sections = deduped
    # Fix first section start to 0
    sections[0] = {**sections[0], 'start': 0}
    # Add path and end
    result = []
    for i, s in enumerate(sections):
        end = sections[i+1]['start'] if i+1 < len(sections) else duration
        result.append({
            'path': str(i+1),
            'title': s['title'],
            'start': s['start'],
            'end': end,
        })
    return result

# %% ../nbs/03_toc.ipynb #d95b70ae
def _build_toc_prompt(segments: list[Segment], # List of Segment from parse_xscript
                      meta: dict # meta.json content
                     ) -> str: # Prompt for LLM
    "Build a prompt that asks the LLM to identify topic transitions and return section titles with start times."
    lines = []
    for s in segments:
        mm = int(s.start // 60)
        ss = int(s.start % 60)
        lines.append(f"[{mm:02d}:{ss:02d}] {s.text}")
    transcript = '\n'.join(lines)

    title = meta.get('title', '')
    channel = meta.get('channel', '')
    desc = meta.get('description', '')

    return f"""You are a structural editor for YouTube video transcripts.

Video info:
- Title: {title}
- Channel: {channel}
- Description: {desc}

Transcript:
{transcript}

Task:
Read the transcript and identify topic transitions. For each section, provide:
- title: concise English section title
- start: start time in integer seconds

Aim for 7-15 sections. Be faithful to transcript timestamps."""

class RawTocSection(BaseModel):
    "One section as returned by the TOC LLM — title + start time only."
    title: str = Field(description="Concise English section title")
    start: int = Field(ge=0, description="Start time in integer seconds")

class TocLLMResult(BaseModel):
    "Structured output from the TOC generation LLM call."
    sections: list[RawTocSection]

def _call_llm(prompt: str # Full prompt
             ) -> list[dict]: # [{title, start}, ...]
    "Call OpenAI gpt-5.4 with Pydantic-generated schema, return raw section list."
    import openai
    client = openai.OpenAI()
    response = client.chat.completions.create(
        model='gpt-5.4',
        response_format={
            "type": "json_schema",
            "json_schema": {
                "name": "generate_toc",
                "schema": TocLLMResult.model_json_schema(),
            },
        },
        messages=[{"role": "user", "content": prompt}],
    )
    result = TocLLMResult.model_validate_json(response.choices[0].message.content)
    return [s.model_dump() for s in result.sections]

# %% ../nbs/03_toc.ipynb #795bea0d
import sys
from fastcore.script import call_parse
from .core import format_header, format_toc_line
from .fetch import _DEFAULT_ROOT, _update_last_used, _glob_srt
from .xscript import parse_xscript

def generate_toc(video_id: str, # Exact video_id
                 root: Path = None, # Root cache directory
                 refresh: bool = False, # Delete cached toc/summaries and regenerate
                ) -> list[dict]: # Normalized sections
    "Generate toc.json for a cached video. Returns sections list."
    root = root or _DEFAULT_ROOT
    d = root / video_id
    meta_path = d / 'meta.json'
    toc_path = d / 'toc.json'
    srt_files = _glob_srt(d)
    if not (meta_path.exists() and srt_files):
        raise SystemExit(f"Not cached: {video_id}")

    if refresh:
        if toc_path.exists(): toc_path.unlink()
        sum_path = d / 'summaries.json'
        if sum_path.exists():
            sum_path.unlink()
            print('Invalidated summaries.json (depends on toc)', file=sys.stderr)

    # Return cached toc if exists
    if toc_path.exists():
        return json.loads(toc_path.read_text(encoding='utf-8'))['sections']

    meta = json.loads(meta_path.read_text(encoding='utf-8'))
    segments = parse_xscript(srt_files[0])
    prompt = _build_toc_prompt(segments, meta)
    raw = _call_llm(prompt)
    sections = _normalize_sections(raw, meta.get('duration', 0))

    toc_path.write_text(
        json.dumps({'sections': sections}, indent=2, ensure_ascii=False),
        encoding='utf-8')
    _update_last_used(meta_path)
    return sections

@call_parse
def yttoc_toc(video_id: str, # Exact video_id
              root: str = None, # Root cache directory
              refresh: bool = False, # Regenerate toc (and invalidate summaries)
             ):
    "Generate and display Table of Contents for a cached video."
    root = Path(root) if root else _DEFAULT_ROOT
    d = root / video_id
    meta_path = d / 'meta.json'
    if not meta_path.exists():
        raise SystemExit(f"Not cached: {video_id}")

    meta = json.loads(meta_path.read_text(encoding='utf-8'))
    sections = generate_toc(video_id, root, refresh=refresh)

    print(format_header(meta))
    print()
    url = meta.get('webpage_url', '')
    for s in sections:
        print(format_toc_line(s, url))
