"""Parse and normalize YouTube caption SRT files into xscript segments"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/02_xscript.ipynb.

# %% auto #0
__all__ = ['parse_xscript', 'yttoc_raw', 'yttoc_txt']

# %% ../nbs/02_xscript.ipynb #a1000004
import re
from pathlib import Path

# %% ../nbs/02_xscript.ipynb #a1000006
_TIME_RE = re.compile(r'(\d+):(\d+):(\d+),(\d+)\s*-->\s*(\d+):(\d+):(\d+),(\d+)')
_SPEAKER_RE = re.compile(r'^>>\s*')

def _ts_to_sec(h: int, m: int, s: int, ms: int) -> float:
    "Convert HH:MM:SS,mmm components to float seconds."
    return h*3600 + m*60 + s + ms/1000

def _parse_srt(content: str) -> list[tuple[float, float, str]]:
    "Parse SRT text into raw (start, end, content) tuples. Raise ValueError on malformed blocks."
    cues = []
    for block in re.split(r'\r?\n\r?\n+', content.strip()):
        lines = [l for l in block.splitlines() if l.strip()]
        if not lines: continue  # whitespace-only block
        # Find the --> line (may be at [0] if index line is missing, otherwise [1])
        time_idx = None
        for i, line in enumerate(lines):
            if _TIME_RE.search(line):
                time_idx = i
                break
        if time_idx is None:
            raise ValueError(f"Malformed SRT block (no timestamp): {block[:80]!r}")
        m = _TIME_RE.search(lines[time_idx])
        h1, m1, s1, ms1, h2, m2, s2, ms2 = map(int, m.groups())
        start = _ts_to_sec(h1, m1, s1, ms1)
        end = _ts_to_sec(h2, m2, s2, ms2)
        text_lines = lines[time_idx+1:]
        cues.append((start, end, '\n'.join(text_lines)))
    return cues

def _normalize_cue(content: str) -> str:
    "Split lines, strip each, drop empty, strip leading '>> ' per line, join with space."
    out = []
    for line in content.splitlines():
        line = line.strip()
        if not line: continue
        line = _SPEAKER_RE.sub('', line)
        if line: out.append(line)
    return ' '.join(out)

def _norm_token(t: str) -> str:
    "Normalize a token for overlap comparison (not for output)."
    return t.lower().strip('.,?!;:"\'()[]{}')

def _find_overlap(prev: list[str], curr: list[str]) -> int:
    "Return longest k where prev[-k:] matches curr[:k] under _norm_token."
    max_k = min(len(prev), len(curr))
    prev_n = [_norm_token(t) for t in prev]
    curr_n = [_norm_token(t) for t in curr]
    for k in range(max_k, 0, -1):
        if prev_n[-k:] == curr_n[:k]:
            return k
    return 0

def parse_xscript(path: str | Path # Path to SRT file
                 ) -> list[dict]: # List of {start, end, text} segments
    "Parse SRT file into normalized xscript segments (dedup rolling-window overlap)."
    content = Path(path).read_text(encoding='utf-8')
    raw_cues = _parse_srt(content)

    segments = []
    prev_raw_tokens: list[str] = []
    prev_end = 0.0

    for start, end, raw_content in raw_cues:
        text = _normalize_cue(raw_content)
        curr_tokens = text.split()
        if not curr_tokens:
            continue

        # Dedup only when time ranges overlap
        if segments and start < prev_end:
            k = _find_overlap(prev_raw_tokens, curr_tokens)
            if k > 0:
                curr_tokens = curr_tokens[k:]
                start = prev_end
                # Preserve invariant start <= end. Can happen when the current
                # cue is fully contained within the previous cue's time window.
                if start > end:
                    end = start

        # Save raw tokens for next iteration's comparison (not deduped)
        prev_raw_tokens = text.split()
        prev_end = end

        if curr_tokens:
            segments.append({
                'start': start,
                'end': end,
                'text': ' '.join(curr_tokens),
            })

    return segments

# %% ../nbs/02_xscript.ipynb #bcd5731c
import json
from fastcore.script import call_parse
from .core import fmt_duration, format_header, slice_segments
from .fetch import _DEFAULT_ROOT, _update_last_used, _glob_srt

def _load_segments(video_id: str, section: str, root: str | None
                  ) -> tuple[dict, list[dict], dict | None, Path]:
    "Load meta, parse xscript, optionally slice to section. Return (meta, segments, sec_info, meta_path)."
    root = Path(root) if root else _DEFAULT_ROOT
    d = root / video_id
    meta_path = d / 'meta.json'
    srt_files = _glob_srt(d)
    if not (meta_path.exists() and srt_files):
        raise SystemExit(f"Not cached: {video_id}")

    meta = json.loads(meta_path.read_text(encoding='utf-8'))
    segments = parse_xscript(srt_files[0])
    sec_info = None

    if section:
        toc_path = d / 'toc.json'
        if not toc_path.exists():
            raise SystemExit(f"No toc.json for {video_id}. Run yttoc-toc first.")
        toc = json.loads(toc_path.read_text(encoding='utf-8'))
        sec_info = next((s for s in toc['sections'] if s['path'] == section), None)
        if sec_info is None:
            raise SystemExit(f"Section {section} not found")
        segments = slice_segments(segments, sec_info['start'], sec_info['end'])

    return meta, segments, sec_info, meta_path

@call_parse
def yttoc_raw(video_id: str, # Exact video_id
              section: str = '', # Section path (e.g. "3"); empty for full transcript
              root: str = None, # Root cache directory (default: ~/.cache/yttoc)
             ):
    "Display transcript for a cached video (full or by section)."
    meta, segments, sec_info, meta_path = _load_segments(video_id, section, root)

    print(format_header(meta))
    print()

    if sec_info is not None:
        s_start = fmt_duration(sec_info['start'])
        s_end = fmt_duration(sec_info['end'])
        print(f"## {section}. {sec_info['title']} ({s_start} - {s_end})")

    for s in segments:
        mm = int(s['start'] // 60)
        ss = int(s['start'] % 60)
        print(f"[{mm:02d}:{ss:02d}] {s['text']}")

    _update_last_used(meta_path)

@call_parse
def yttoc_txt(video_id: str, # Exact video_id
              section: str = '', # Section path (e.g. "3"); empty for full transcript
              root: str = None, # Root cache directory (default: ~/.cache/yttoc)
             ):
    "Display transcript as plain prose with no timestamps."
    meta, segments, sec_info, meta_path = _load_segments(video_id, section, root)

    print(format_header(meta))
    print()

    if sec_info is not None:
        s_start = fmt_duration(sec_info['start'])
        s_end = fmt_duration(sec_info['end'])
        print(f"## {section}. {sec_info['title']} ({s_start} - {s_end})")
        print()

    print(' '.join(s['text'] for s in segments))

    _update_last_used(meta_path)
